### ISSUE TITLE
Scripthook Error

### ISSUE THREAD

**Issue by cosmokid** [UnknownModder/rdr3-nativedb-data#1]
I get a really weird annoying texture bug using Scripthook.

[https://i.imgur.com/QVvDI6o.jpg](https://i.imgur.com/QVvDI6o.jpg)

**Comment by UnknownModder** [comment]
I have not released my script hook yet. This isn't the right place for bug reports anyway.
Closed.

**Comment by cosmokid** [comment]
> I have not released my script hook yet. This isn't the right place for bug reports anyway.
> Closed.

Oh sorry, I thought you were the owner of ( https://www.nexusmods.com/reddeadredemption2/mods/20 ) ?
